# name: env
# on:
#  push

# jobs:
#  env:
#   runs-on: ubuntu-latest
#   env:
#    APP: demo
#   steps:
#    -run: echo $APP


# name: Env

# on:
#  push

# jobs:

#  env:
#   runs-on: ubuntu-latest
#   env:
#    APP: demo
#   steps:
#    - run: echo $APP
# =======
  env-demo:
    runs-on: ubuntu-latest

    env:
      APP_NAME: pipeline-demo
      VERSION: 1.0

    steps:
      - name: Print App Name
        run: echo "App is $APP_NAME"

      - name: Print Version
        run: echo "Version is $VERSION"

